/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cube.glb 
Author: artwork guide (https://sketchfab.com/artworkguide)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cube-48b8725fd63a4562abc181cf09b1333a
Title: Cube
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cube.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} position={[48.657, -4.766, 48.864]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cube.glb')
